/**
 * A file to be generated by an adapter.
 * Adapters return these; the caller handles writing to disk.
 */
export interface GeneratedFile {
  /** Relative path from project root (e.g., "skills/whyspec-plan/SKILL.md") */
  path: string;
  /** File content */
  content: string;
}

/** The 6 WhySpec commands that adapters generate config for. */
export const WHYSPEC_COMMANDS = [
  "plan",
  "execute",
  "capture",
  "show",
  "search",
  "debug",
] as const;

export type WhySpecCommand = (typeof WHYSPEC_COMMANDS)[number];

/** One-line descriptions for each command, used across all adapters.
 * IMPORTANT: These must be trigger conditions ("Use when..."), not workflow summaries.
 * Summary descriptions cause Claude to shortcut the skill body. */
export const COMMAND_DESCRIPTIONS: Record<WhySpecCommand, string> = {
  plan: "Use when planning a code change, capturing decisions before coding, or setting up the Decision Bridge",
  execute: "Use when starting implementation, continuing work, or executing tasks from a WhySpec plan",
  capture: "Use after coding to preserve reasoning — resolves the Decision Bridge with actual outcomes",
  show: "Use when reviewing the full story of a change — intent, design, tasks, and Decision Bridge delta",
  search: "Use when looking for why something was built a certain way or finding past decisions",
  debug: "Use when encountering any bug, test failure, or unexpected behavior — before proposing fixes",
};

/** Gray placeholder text shown beside slash commands in UIs that support it. */
export const COMMAND_ARGUMENT_HINTS: Record<WhySpecCommand, string> = {
  plan: "<change-name-or-description>",
  execute: "[change-name]",
  capture: "[change-name]",
  show: "[change-name]",
  search: "<query> [--domain <domain>]",
  debug: "<bug-description-or-change-name>",
};
