/**
 * A file to be generated by an adapter.
 * Adapters return these; the caller handles writing to disk.
 */
export interface GeneratedFile {
  /** Relative path from project root (e.g., ".claude/skills/whyspec-plan/SKILL.md") */
  path: string;
  /** File content */
  content: string;
}

/** The 6 WhySpec commands that adapters generate config for. */
export const WHYSPEC_COMMANDS = [
  "plan",
  "execute",
  "capture",
  "show",
  "search",
  "debug",
] as const;

export type WhySpecCommand = (typeof WHYSPEC_COMMANDS)[number];

/** One-line descriptions for each command, used across all adapters. */
export const COMMAND_DESCRIPTIONS: Record<WhySpecCommand, string> = {
  plan: "Declare intent and plan decisions before coding",
  execute: "Implement from plan with full reasoning context",
  capture: "Save the reasoning behind what was built",
  show: "View the full story of a change with Decision Bridge delta",
  search: "Search past decisions and reasoning across all changes",
  debug: "Debug with the scientific method and capture root cause",
};
